### ISSUE TITLE
Storage / retrieval of files?

### ISSUE THREAD

**Issue by Grayda** [Grayda/sphere-documentation#2]
Just in case the Ninja Blocks website goes offline (and the GitHub repos disappear too) it'd be nice to know how we can either:
1. Extract or recreate these files ourselves (e.g. Error codes for factory reset. They're in Jon Seymour's Gist now, but can we get these codes from source code if he deletes his account?)
2. Store these files long-term (e.g. the Factory Rest USB image)

Thoughts?

**Comment by MartynWilliams** [comment]
The gist for the reset codes returns a 404 so I think we need to act
quickly and get the extract done asap.

**Comment by MartynWilliams** [comment]
David,

I think we need to ask Elliot to export the contents of the Discourse
instance for NinjaBlocks, my understanding is that we can host our own
instance, or we can import it into Postgres.

Either way we really do need to find a new home for the content. I have
still not heard from my employer we can host it on one of our public
server, so we may need an interim solution.

I've been selectively converting the content ito markdown format, but it is
slow and I need to find a way to cover the entire DB so we have a copy of
the group.

I'll ask Elliot if he is an admin of the NinjaBlock site and if he can
assist.

Martyn

**Comment by paulcull** [comment]
Discuss is not a free option, so we need to try to see if we can get it moved to something free, and some warning for any downtime. May be something to talk about at the meetup with the ninja's

**Comment by Grayda** [comment]
@paulcull I thought they used DIscourse, which is [open source](https://github.com/discourse/discourse) if you can run Ruby on Rails. The NB guys have said they'll keep the forums open, as the cost is minimal (a RoR host and a discourse install). I don't know what they're paying for GitHub (that is, I don't know what repos are still private, so I don't know how much it costs) so that's something we can ask. 

On a separate note, I've updated the factory reset wiki page with a Gist I created of the error codes. I ran some regex through a factory reset script still on GitHub and extracted codes. I don't know if it's all of the codes, but there's a fair amount in there: https://gist.github.com/Grayda/cc9247cdce87615c0f0d

**Comment by Vertikar** [comment]
@Grayda Is there a need for us to consider paying for github anytime soon? I thought the only real reason for paying (as an individual at least) was private repositories, which I don't see a need for right now, I'm open to idea of having stuff private, but only if we need to.

**Comment by Grayda** [comment]
I'm not sure what we'd have that we'd need to keep private. The NB guys would, with NDAs and stuff they were privately working on that isn't ready for prime time. But I guess the stuff we'd be working on would be stuff that's already been released and in need of patching up?

I guess if the time comes and we need private repos, we could either host them elsewhere (to avoid paying) or we could all chip in for a private account and become collaborators of private repos. But that's a bit further down the road.

In the meantime, I think the documentation is going rather well. I've been poking around with MQTT some more, hoping to figure out how everything "pieces" together so we can create a high-level flowchart or diagram of how the Sphere runs as one big happy software piece.

**Comment by theshaun** [comment]
> we could all chip in for a private account and become collaborators of private repos

In which case an organisation could be setup to handle the onslaught of repos in a more manageable way, similar to how the ninja's already have it

**Comment by Vertikar** [comment]
We could setup an org right now if we wanted, its free, but you don't get any private repos like the individual level:
https://github.com/pricing

**Comment by paulcull** [comment]
are we running before we can walk ? I think we've still got a long way to go before we need this ?

**Comment by Grayda** [comment]
@Vertikar: That's something to ponder. Because we're only working with one repo (i.e. this one), would this be enough for now until we need more, then decide?
@paulcull: I agree. No harm in researching though :)
