### ISSUE TITLE
Attribution when using material / licensing?

### ISSUE THREAD

**Issue by Grayda** [Grayda/sphere-documentation#3]
Do we need to attribute / cite when including stuff from the forums? Do we also need to stick somewhere, an MIT license (as most code from Ninja Blocks is MIT, I think)? [This page on LED images](https://github.com/Grayda/sphere-documentation/wiki/LED-Images-and-their-meaning) is from the forums (written by Jon, I think?). I know it's a WIP, but let's say that page sticks around. Should we be attributing / licensing / whatever?

More of a question, really. I'm not a lawyer, so I don't know much about this area.

**Comment by Vertikar** [comment]
Probably cite it more for a reference rather than legal perspective, helps
us in the future. That said we'd really need to find out if the forums has a license under the
user agreement/terms of use e.g MIT, creative commons etc. to be 100% sure.

If not I'd probably assume it's public domain and safe for us to use
without attribution, but I'd still suggest citing it for future reference.

**Comment by Grayda** [comment]
[Looks like it's a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License](https://discuss.ninjablocks.com/tos)

> 3 User Content License
> User contributions are licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License. Without limiting any of those representations or warranties, Ninja Blocks has the right (though not the obligation) to, in Ninja Blocks’s sole discretion (i) refuse or remove any content that, in Ninja Blocks’s reasonable opinion, violates any Ninja Blocks policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in Ninja Blocks’s sole discretion. Ninja Blocks will have no obligation to provide a refund of any amounts previously paid.

Closing, as we now know what license the forums are under, and what license code is under too. I agree, we should cite for reference where possible.
